---
- hosts: web
  remote_user: testUser
  tasks:
    - name: Install nginx
      become: true
      package:
        name: nginx
        state: latest
    - name: Starting nginx 
      become: true
      service: 
        name: nginx
        state: started
        masked: no
