---
# tasks file for nginx
    - name: Install nginx
      become: true
      package:
        name: nginx
        state: present
    - name: "Make index.html"
      template:
        src: templates/index.html.j2
        dest: "{{ ansible_user_dir }}/index.html"
    - name: Starting nginx
      become: true
      systemd:
        name: nginx
        enabled: true
        masked: no
    - name: Install curl
      become: true
      package:
        name: curl
        state: present
    - name: Curl
      command: "curl {{ ansible_facts.default_ipv4.address }}"
...